steps:
  build-and-test-and-push:
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: Containerfile
      registry: quay.io
      repo: iamleeg/onthewing
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
    when:
      branch: main
      event: [push, manual]

  update-manifest:
    image: alpine/git
    secrets: [ codeberg_token ]
    commands:
      # Configure git client identity
      - git config user.name "Woodpecker CI"
      - git config user.email "ci@example.com"
      # Replace image tag in deployment manifest with the current commit SHA
      - 'sed -i "s|image: quay.io/iamleeg/onthewing.*|image: quay.io/iamleeg/onthewing:${CI_COMMIT_SHA}|" k8s/deployment.yaml'
      - git add k8s/deployment.yaml
      # Commit changes and use [skip ci] to prevent build loops
      - 'git commit -m "ci: update image tag to ${CI_COMMIT_SHA} [skip ci]"'
      # Verify if the secret is successfully injected by Woodpecker
      - '[ -z "$$CODEBERG_TOKEN" ] && echo "ERROR: CODEBERG_TOKEN is empty!" || echo "CODEBERG_TOKEN is set."'
      # Push back to Codeberg repository using the oauth token
      - 'git push https://leeg:$$CODEBERG_TOKEN@codeberg.org/leeg/onthewing.git main'
    when:
      branch: main
      event: [push, manual]





