apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: onthewing
build:
  local:
    push: false
  artifacts:
    - image: quay.io/iamleeg/onthewing
      context: .
      custom:
        buildCommand: podman build -t $IMAGE -f Containerfile . && podman save -o /tmp/otw.tar $IMAGE && minikube image load /tmp/otw.tar
        dependencies:
          paths:
            - "**/*"
    - image: localhost/local/firebase-emulator
      context: local-dev/emulator
      custom:
        buildCommand: podman build -t $IMAGE -f $BUILD_CONTEXT/Dockerfile $BUILD_CONTEXT && podman save -o /tmp/firebase-emulator.tar $IMAGE && minikube image load /tmp/firebase-emulator.tar
        dependencies:
          paths:
            - "Dockerfile"
            - "firebase.json"
            - "storage.rules"
manifests:
  kustomize:
    paths:
      - local-dev
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: onthewing-svc
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: firebase-emulator-svc
    port: 9099
    localPort: 9099
  - resourceType: service
    resourceName: firebase-emulator-svc
    port: 9199
    localPort: 9199
  - resourceType: service
    resourceName: firebase-emulator-svc
    port: 4000
    localPort: 4000
