apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: onthewing
build:
  local:
    push: false
  artifacts:
    - image: quay.io/iamleeg/onthewing
      context: .
      custom:
        buildCommand: podman build -t $IMAGE -f Containerfile . && podman save -o /tmp/otw.tar $IMAGE && minikube image load /tmp/otw.tar
        dependencies:
          paths:
            - "**/*"
manifests:
  kustomize:
    paths:
      - local-dev
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: onthewing-svc
    port: 80
    localPort: 8080
