apiVersion: apps/v1
kind: Deployment
metadata:
  name: onthewing
  labels:
    app: onthewing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onthewing
  template:
    metadata:
      labels:
        app: onthewing
    spec:
      containers:
        - name: onthewing
          image: quay.io/iamleeg/onthewing:1cf530248e2d664b5bb438759390f4dadaa7f286
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /WebObjects/OnTheWing.woa
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /WebObjects/OnTheWing.woa
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
