apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onthewing-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - journalonthewing.co.uk
        - www.journalonthewing.co.uk
      secretName: onthewing-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onthewing-svc
                port:
                  number: 80
