apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onthewing-ingress
  annotations:
    # To add SSL later, you can add cert-manager annotations here
spec:
  ingressClassName: "nginx" # If using Nginx Ingress Controller (common in Linode/Minikube)
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onthewing-svc
                port:
                  number: 80
