apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../k8s
  - firebase-emulator.yaml

patches:
  - target:
      kind: Deployment
      name: onthewing
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: DB_HOST
            value: host.minikube.internal
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: onthewing-eedce-database
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: ""
          - name: GCS_BUCKET
            value: onthewing-eedce.firebasestorage.app
          - name: GCS_API_BASE_URL
            value: http://firebase-emulator-svc:9199
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts
      - op: remove
        path: /spec/template/spec/containers/1
      - op: remove
        path: /spec/template/spec/volumes
  - patch: |-
      $patch: delete
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: onthewing
        namespace: argocd

